// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/activate-subscription": {
            "post": {
                "description": "add subscription if paymentToken has not been expired",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "post page",
                "parameters": [
                    {
                        "type": "string",
                        "description": "jwt token for authentification",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "paymentToken",
                        "name": "paymentToken",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.PaymentToken"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "subscriptionID",
                        "schema": {
                            "type": "int"
                        }
                    },
                    "400": {
                        "description": "activate subscription is impossible",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "not authorised or invalid token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "token has been expired",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error of activating subscription",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/last-subscription-info": {
            "get": {
                "description": "get last subscription info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "get page",
                "parameters": [
                    {
                        "type": "string",
                        "description": "jwt token for authentification",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.SubscriptionInfo"
                        }
                    },
                    "400": {
                        "description": "get last subscription info is impossible",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "not authorised or invalid token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "token has been expired",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error of getting last subscription info",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/news": {
            "get": {
                "description": "get news if last subscription is active",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "news"
                ],
                "summary": "get page",
                "parameters": [
                    {
                        "type": "string",
                        "description": "jwt token for authentification",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.News"
                        }
                    },
                    "400": {
                        "description": "get news is impossible",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "not authorised or invalid token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "token has been expired or current subscription is not active",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error of getting news",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/set-new-subscription": {
            "post": {
                "description": "choose subscriptionType and get paymentToken if last subscription is not active",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "post page",
                "parameters": [
                    {
                        "type": "string",
                        "description": "jwt token for authentification",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": " ID, TypeName, Duration, Price",
                        "name": "subscription_type",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.SubscriptionType"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "paymentToken",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "set new subscription is impossible",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "not authorised or invalid token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "token has been expired",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error of setting new subscription",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/subscription-types": {
            "get": {
                "description": "get subscriptionTypes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptionTypes"
                ],
                "summary": "get subscriptionTypes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "jwt token for authentification",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.SubscriptionType"
                            }
                        }
                    },
                    "401": {
                        "description": "not authorised or invalid token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "token has been expired",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error of getting subscription types",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "login by login and password",
                "tags": [
                    "users"
                ],
                "summary": "login page",
                "parameters": [
                    {
                        "description": "Login, Password",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Credentials"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "login successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "login is impossible",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error with login or incorrect login or password or login is impossible",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "register by login and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "register page",
                "parameters": [
                    {
                        "description": "Login, Password",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Credentials"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "register successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "register is impossible",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error with register or incorrect login or password",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.Credentials": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string",
                    "example": "user"
                },
                "password": {
                    "type": "string",
                    "example": "qwerty"
                }
            }
        },
        "entity.News": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "news"
                }
            }
        },
        "entity.PaymentToken": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "entity.SubscriptionInfo": {
            "type": "object",
            "properties": {
                "end_date": {
                    "type": "string",
                    "example": "2006-01-02T15:04:06Z"
                },
                "start_date": {
                    "type": "string",
                    "example": "2006-01-02T15:04:05Z"
                },
                "subscription_id": {
                    "type": "integer",
                    "example": 1
                },
                "subscription_status": {
                    "description": "1-active, 0-not active",
                    "type": "integer",
                    "example": 1
                },
                "subscription_type_name:": {
                    "type": "string",
                    "example": "1 second"
                }
            }
        },
        "entity.SubscriptionType": {
            "type": "object",
            "properties": {
                "duration": {
                    "description": "1/3/6/12",
                    "type": "integer",
                    "example": 1
                },
                "price": {
                    "type": "integer",
                    "example": 10
                },
                "subscription_type_id": {
                    "type": "integer",
                    "example": 1
                },
                "type_name": {
                    "type": "string",
                    "example": "1 second"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "System Of Subscriptions API",
	Description:      "API for Golang Project System of Subscriptions",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,

}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
